#!/bin/bash



##uznal jsem za vhodne, aby soubory v sobe nemely mezeru. Takove delaji jen bordel
##dale predpokladam, ze adresa neni ve tvaru hhhhhhhhhhhhhwww.johan.cz, prototze na zacatku cesty 
##muze byt cokoliv... http, ftp atd... Libovolny formular


if [ "$1" == --help ]; then

      echo "This program will grep url media from HTML."
      echo " "
  
      echo "Using: "
      echo "getmedia [-arg] [source]"

      echo "  "
      echo " Arguments: "
      echo " -s for sound"
      echo " -i for images"
      echo " --help for help"
      echo " Created by Ondrej Michalek"



elif [ "$1" == "-i"  ]; then 

            cat $2 |  grep -oE '\b(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.png
            cat $2 |  grep -oE 'www.[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.png
            cat $2 |  grep -oE '\b(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.jpg
            cat $2 |  grep -oE 'www.[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.jpg
            cat $2 |  grep -oE '\b(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.svg
            cat $2 |  grep -oE 'www.[-A-Za-z0-9+&@#/%?=_|!:,.;]*[-A-Za-z0-9+&@#/%=_|]'.svg
           
  
elif [ "$1" == "-s" ] ; then 
              
            cat $2 |  grep -oE '\b(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.wav
            cat $2 |  grep -oE 'www.[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.wav
            cat $2 |  grep -oE '\b(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.mp3
            cat $2 |  grep -oE 'www.[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.mp3
            cat $2 |  grep -oE '\b(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.ogg
            cat $2 |  grep -oE 'www.[-A-Za-z0-9+&@#/%?=_|!:,.;]*[-A-Za-z0-9+&@#/%=_|]'.ogg
            
else                 
            cat $1 |  grep -oE '\b(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.png
            cat $1 |  grep -oE 'www.[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.png
            cat $1 |  grep -oE '\b(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.jpg
            cat $1 |  grep -oE 'www.[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.jpg
            cat $1 |  grep -oE '\b(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.svg
            cat $1 |  grep -oE 'www.[-A-Za-z0-9+&@#/%?=_|!:,.;]*[-A-Za-z0-9+&@#/%=_|]'.svg
            cat $1 |  grep -oE '\b(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.wav
            cat $1 |  grep -oE 'www.[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.wav
            cat $1 |  grep -oE '\b(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.mp3
            cat $1 |  grep -oE 'www.[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.mp3
            cat $1 |  grep -oE '\b(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]'.ogg
            cat $1 |  grep -oE 'www.[-A-Za-z0-9+&@#/%?=_|!:,.;]*[-A-Za-z0-9+&@#/%=_|]'.ogg
fi;
