#!/bin/bash

if [ "$1" == --help ]; then

      echo "This program will grep url media from HTML."
      echo " "
  
      echo "Using: "
      echo "getmedia [-arg] [source]"

      echo "  "
      echo " Arguments: "
      echo " -s for sound"
      echo " -i for images"
      echo " --help for help"
      echo " Created by Ondrej Michalek"



elif [ "$1" == "-i"  ]; then 
            cat $2 |  grep -o 'https\?://[^ "]*\.png' 
            cat $2 |  grep -o 'https\?://[^ "]*\.jpg'
            cat $2 |  grep -o 'https\?://[^ "]*\.svg' 
           
  
elif [ "$1" == "-s" ] ; then 
              
            cat $2 |  grep -o 'https\?://[^ "]*\.wav'
       	    cat $2 |  grep -o 'https\?://[^ "]*\.mp3'
            cat $2 |  grep -o 'https\?://[^ "]*\.ogg'
            
else                 
            cat $1 |  grep -o 'https\?://[^ "]*\.png'
            cat $1 |  grep -o 'https\?://[^ "]*\.jpg'
            cat $1 |  grep -o 'https\?://[^ "]*\.svg'
            cat $1 |  grep -o 'https\?://[^ "]*\.wav'
            cat $1 |  grep -o 'https\?://[^ "]*\.mp3'
            cat $1 |  grep -o 'https\?://[^ "]*\.ogg'
fi;
